#ifndef ERRCODE_H
#define ERRCODE_H

#define OPEN_FILE_FAILED -1

#define FF_FIND_CODEC_FAILED -10
#define FF_ALLOC_CONDECCTX_FAILED -11
#define FF_OPEN_CODEC_FAILED -12
#define FF_ALLOC_FRAME_FAILED -13
#define FF_AV_IMAGE_ALLOC_FAILED -14
#define FF_ENCODE_FAILED -15
#endif // ERRCODE_H
